// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ManifestTaskRunner
{
    internal sealed partial class Vsix
    {
        public const string Id = "ManifestTaskRunner.642e7f23-01f4-4f30-8c57-815b72cef483";
        public const string Name = "Manifest Task Runner";
        public const string Description = @"Example of how to create a simple Task Runner Explorer extension";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "TRX";
    }
}
